@startuml
class ML::Clustering::KMeans  {
  {method} BUILDALL
  {method} args-check
  {method} cosine-distance
  {method} distance
  {method} euclidean-distance
  {method} find-clusters
  {method} hamming-distance
  {method} norm
}
ML::Clustering::KMeans --|> ML::Clustering::DistanceFunctions


class "find-clusters" <<routine>> {
}
"find-clusters" --|> Routine
"find-clusters" --|> Block
"find-clusters" --|> Code
"find-clusters" --|> Callable


class ML::Clustering::DistanceFunctions <<role>> {
  {method} args-check
  {method} cosine-distance
  {method} distance
  {method} euclidean-distance
  {method} hamming-distance
}


class "k-means" <<routine>> {
}
"k-means" --|> Routine
"k-means" --|> Block
"k-means" --|> Code
"k-means" --|> Callable


@enduml
